/* Q1
Calculate the total revenue by multiplying Quantity and Unit Price
for each row, then summing all rows.
*/

Total Sales Amount =
SUMX(
    Sales,
    Sales[Quantity] * Sales[UnitPrice]
)


/* Q2
Calculate revenue generated by each individual sale record.
This is a calculated column, so the value is stored for every row.
*/

Line Revenue =
Sales[Quantity] * Sales[UnitPrice]


/* Q3
Find the average selling price across all products.
*/

Average Unit Price =
AVERAGE(Sales[UnitPrice])


/* Q4
Calculate revenue generated only from products
belonging to the Furniture category.
*/

Furniture Revenue =
CALCULATE(
    SUMX(
        Sales,
        Sales[Quantity] * Sales[UnitPrice]
    ),
    Sales[Category] = "Furniture"
)


/* Q5
Calculate the percentage contribution of Furniture Revenue
to the overall Total Sales Amount.
DIVIDE is used to safely handle divide-by-zero scenarios.
*/

Furniture Revenue % =
DIVIDE(
    [Furniture Revenue],
    [Total Sales Amount],
    0
)